# HENAW Algorithm Configuration
# UK Biobank Field Mappings and Training Settings

# UK Biobank Field IDs for Required Biomarkers
ukbb_fields:
  biomarkers:
    crp: 30710  # C-reactive protein
    hba1c: 30750  # Glycated hemoglobin
    creatinine: 30700  # Creatinine
    albumin: 30600  # Albumin
    lymphocyte_pct: 30180  # Lymphocyte percentage
    rdw: 30070  # Red cell distribution width
    ggt: 30730  # Gamma glutamyltransferase
    ast: 30650  # Aspartate aminotransferase
    alt: 30620  # Alanine aminotransferase
  
  demographics:
    age: 21022  # Age at recruitment
    sex: 31  # Sex
    
  outcomes:
    death_date: 40000  # Date of death
    death_cause: 40001  # Primary cause of death
    disease_codes: 41270  # ICD10 diagnoses

# Biological System Groupings
biological_systems:
  inflammation:
    - crp
    - lymphocyte_pct
  metabolism:
    - hba1c
    - ggt
    - alt
    - ast
  organ_function:
    - creatinine
    - albumin
  hematology:
    - rdw
    - lymphocyte_pct

# Model Architecture
model:
  input_dim: 9  # Number of biomarkers
  hidden_dims: [64, 32, 16]  # Hierarchical encoder dimensions
  system_embedding_dim: 16
  dropout_rate: 0.2
  activation: 'relu'
  
  # Adaptive weighting parameters
  adaptive_weighting:
    lambda_param: 1.0
    update_frequency: 10  # Update weights every N epochs
    temperature: 0.5

# Training Configuration
training:
  batch_size: 512
  epochs: 100
  learning_rate: 0.001
  weight_decay: 0.0001
  
  # Multi-task loss weights
  loss_weights:
    age_prediction: 1.0
    mortality: 0.3
    morbidity: 0.2
    
  # Elastic Net regularization
  elastic_net:
    alpha: 0.5  # L1 vs L2 balance
    lambda_reg: 0.01  # Overall regularization strength
    hierarchical_constraint: 2.0  # System-level constraint multiplier
  
  # Optimization
  optimizer: 'adam'
  scheduler:
    type: 'cosine'
    min_lr: 0.00001
    warmup_epochs: 5
  
  # Cross-validation
  n_folds: 5
  stratify_by_age: true
  age_bins: [40, 50, 60, 70]  # Age stratification boundaries
  
  # Data split
  train_ratio: 0.6
  val_ratio: 0.2
  test_ratio: 0.2
  temporal_holdout: true  # Use last 20% chronologically

# Feature Engineering
feature_engineering:
  # Z-score normalization
  age_window: 5  # ±5 years for age-specific normalization
  sex_specific: true
  
  # Non-linear transformations
  transformations:
    type: 'log_distance'  # log(1 + |x - μ|/σ)
    clip_outliers: 5  # Clip at 5 standard deviations
  
  # Interaction features
  interactions:
    - ['crp', 'hba1c']  # Inflammation-metabolism
    - ['creatinine', 'albumin']  # Kidney-liver axis
  
  # Ratio features
  ratios:
    - ['ast', 'alt']  # AST/ALT ratio

# Evaluation Metrics
evaluation:
  metrics:
    - mae  # Mean Absolute Error
    - rmse  # Root Mean Square Error
    - r2  # R-squared
    - c_statistic  # Concordance for mortality
    - icc  # Intraclass Correlation Coefficient
  
  # Performance targets
  targets:
    mae: 5.0  # < 5 years
    c_statistic: 0.75  # > 0.75
    icc: 0.85  # > 0.85

# Infrastructure
infrastructure:
  device: 'cuda'  # 'cuda' or 'cpu'
  num_workers: 8
  pin_memory: true
  mixed_precision: true
  gradient_checkpointing: false
  
  # Memory management
  max_memory_gb: 8
  batch_accumulation_steps: 1

# Logging and Checkpointing
logging:
  log_dir: './logs'
  tensorboard: true
  wandb:
    project: 'henaw-biological-age'
    entity: null  # Set your wandb entity
  
  checkpoint:
    save_dir: './checkpoints'
    save_frequency: 5  # Save every N epochs
    keep_best_k: 3
    monitor_metric: 'val_mae'
    mode: 'min'

# Output Configuration
output:
  results_dir: './results'
  save_predictions: true
  save_feature_importance: true
  generate_clinical_report: true
  
  # Inference settings
  inference:
    batch_size: 1024
    max_latency_ms: 100
    
# Reproducibility
reproducibility:
  seed: 42
  deterministic: true
  benchmark: false